### PR TITLE
Add RJ Kanson

### PR DESCRIPTION
**Pull request by rkanson**

### CODE REVIEW

**Review by abloomston — CHANGES_REQUESTED** [review]
Hi @rkanson thanks for using a WWM guide! Would you mind removing the directory [`workwithme.guide`](https://github.com/rkanson/workwithme.guide/tree/master/workwithme.guide) and the submodule under it (`workwithme.guide/rkanson`)? You only need the top-level submodule added as part of this PR`rkanson`. Thanks!

**Review by clintonPantheon — APPROVED** [review]
👍 lgtm!!! 🎊

**Comment by clintonPantheon** [comment]
> Hi @rkanson thanks for using a WWM guide! Would you mind removing the directory [`workwithme.guide`](https://github.com/rkanson/workwithme.guide/tree/master/workwithme.guide) and the submodule under it (`workwithme.guide/rkanson`)? You only need the top-level submodule added as part of this PR`rkanson`. Thanks!

@abloomston  I am way overdue to say hi!

**Review by clintonPantheon — CHANGES_REQUESTED** [review]
@rkanson see adam's comments.

**Comment by rkanson** [comment]
@abloomston @clintonPantheon Removed that folder! Thought I had removed the submodule, I'm not seeing it when I cat out the .gitmodules file.

**Review by abloomston — APPROVED** [review]
LGTM now! Thanks

**Comment by rkanson** [comment]
Cheers!

**Comment by abloomston** [comment]
@rkanson here you go: http://workwithme.guide/rkanson/

**Pull request merged**
